### ISSUE TITLE
QA-Modules dependent projet not accessible

### ISSUE THREAD

**Issue by cedfou** [Jahia/content-editor#62]
The 'https://github.com/Jahia/QA-Modules' projet doesn't seem to be accessible... (404 error for me)
It is mentionned as a required dependency:
"Requirements
    the qa-module from https://github.com/Jahia/QA-Modules"

How can we test this module?
Regards,

**Comment by dgriffon** [comment]
Hello, the QA module was used because of some hardcoded stuff when we started the project, but it is not the case anymore, but the documentation not updated, thank you for the warning

**Comment by dgriffon** [comment]
Documentation updated.

**Comment by cedfou** [comment]
Ok good news.
Thanks, will try it!

**Comment by rgauthierJahia** [comment]
Hello Cedric, we'll release a beta version of content editor (the future edit engine) in July, version 1.0 is targeted for September. In the meantime, it's not impossible that this repository will be set to private. The documentation has been updated. 
Best,

**Comment by cedfou** [comment]
Thanks, I have already made a copy ;)

The goal is not to use it in our project (for the moment) but to look how we can use GraphQL API to build frontend or extensions UI.
Regards,

**Comment by digitalRomain** [comment]
It does make sense to have a look at the GraphQL calls and at the stack that we're now using (our design system, Apollo and React), since Content Editor will be extendable and customizable in many ways (not in the beta version though). 
Do you mind sharing what kind of extension or frontend do you need to build? That could help us to plan for the right extension points. 
Romain

**Comment by cedfou** [comment]
We don't know yet.
We have a project on the Content&Media manager to add pagination on content/documents browsing §and in EDP also)...
On Content editor, it's just curiosity.
